name: Cherry Pick from Remote

on:
  workflow_dispatch:  # Elle başlatmak için

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    steps:
    - name: Bu repoyu klonla
      uses: actions/checkout@v4

    - name: Git kullanıcı bilgilerini ayarla
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Kaynak repoyu ekle ve fetch et
      run: |
        git remote add upstream https://github.com/sundrams-playground/kernel_samsung_exynos9610.git
        git fetch upstream wip

    - name: Yeni branch oluştur
      run: |
        git checkout -b cherry-pick-upstream

    - name: Cherry-pick işlemi
      run: |
        COMMITS=(
       e79f371ee2654dffc9ecc0ef1a5bb14f63ea7bd4
       b9f8f6721ee1504900a8154516743240cfea00b1
       a5fbf791ef2f843ab927479ac64c988412def0cf
       6f2d3fc1d627f6342a6652bcb4d691fd71312e042
       ecdab50e91645b9bf3224e9ff26a777613984746
       6d213829dba6b11b066b36ff76d998d6e25fb12
               )
          

        for commit in "${COMMITS[@]}"; do
          echo "Cherry-picking $commit..."
          git cherry-pick $commit || {
            echo "⛔ Çatışma oluştu: $commit"
            exit 1
          }
        done

    - name: Push changes to origin
      run: |
        git push origin cherry-pick-upstream --force
